### ISSUE TITLE
Unable to install VS019 version of Serene extension

### ISSUE THREAD

**Issue by eduard-schwenk** [serenity-is/Serene#89]
Hello, 
i have trouble with the current version of Serene extension from the marketplace:

Identifier         : Serene_SerenityApplicationTemplateVS2019
Name              : Serene (VS2019)
Version            : 5.2.4.0

Used Visual Studio:
Visual Studio Professional 2019  v16.11.9

The VSIX installer throw an exception:
- System.InvalidOperationException: A value for 'VsixPackage' needs to be specified in the catalog.

Maybe here is an error in the vsix package config?

Installation on another machine with the latest VS2019 update results with the same error.

Thanks in advance

**Comment by VictorTomaili** [comment]
Maybe there is an issue in vsix because of our automation to create vsix package for vs2019. Or one of Visual Studio 2019 update is broke the vsix installation. But this is the last version of serene which is supported by vs2019. The next version of serene (.net 6) is not supported by vs2019 anymore. 
See this https://docs.microsoft.com/en-us/visualstudio/releases/2019/compatibility#-visual-studio-2019-support-for-net-development

Install newer version of Visual Studio if possible. You can install community edition of Visual Studio 2022 and latest serene package. Then open the project with vs2019 if you have license for vs2019 only. (for .net 5 versions of vsix)

And you can use discussions on this repository to be a part of serenity community. https://github.com/serenity-is/Serenity/discussions

**Comment by eduard-schwenk** [comment]
I've found one of the previous vsix files:
The package with version 5.0.51.8 works and can be installed on latest VS2019 version,
so it seems that the issue is in the latest build of Serene extension. 
VS2022 works fine.

**Comment by VictorTomaili** [comment]
hello @eduard-schwenk

Can you try to latest 2019 version of serene extension? We publish an update with the package version to`5.2.4.1`. The issue should be fixed for vs2019 

If everythings is fine, this release will be last release extension for 2019. 
The .net 6 version of serene is continue for the vs2022

**Comment by eduard-schwenk** [comment]
Hello @VictorTomaili 
i've tested on 2 different machines, .. setup works fine now.
Thanks a lot!
